---
# tasks file for k3s_registry
#
#
- name: create folder 
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: '0755'


- name: k3s registry
  ansible.builtin.copy:
    content: |
      mirrors:
        "infra:5000":
          endpoint:
           - "http://infra:5000"
    dest: /etc/rancher/k3s/registries.yaml
    owner: root
    group: root
    mode: '0644'
  notify: restart k3s
