#!/usr/sbin/nft -f

flush ruleset

table ip nat {
       chain postrouting {
                type nat hook postrouting priority srcnat; policy accept;
                oifname "enp0s3" masquerade
                ip daddr 10.0.20.11 tcp dport 30050 masquerade
                ip daddr 10.0.40.10 tcp dport 3000 masquerade
                ip daddr 10.0.40.10 tcp dport 8080 masquerade
                ip daddr 10.0.40.10 tcp dport 9090 masquerade
                ip daddr 10.0.40.10 tcp dport 3001 masquerade
                ip daddr 10.0.40.10 tcp dport 9093 masquerade
       }
       chain prerouting {
                type nat hook prerouting priority dstnat; policy accept;
                iifname "enp0s8" tcp dport 80 dnat to 10.0.20.11:30050
                iifname "enp0s8" tcp dport 3000 dnat to 10.0.40.10:3000
                iifname "enp0s8" tcp dport 8080 dnat to 10.0.40.10:8080
                iifname "enp0s8" tcp dport 9090 dnat to 10.0.40.10:9090
                iifname "enp0s8" tcp dport 3001 dnat to 10.0.40.10:3001
                iifname "enp0s8" tcp dport 9093 dnat to 10.0.40.10:9093
       }
}


table inet filter {
	chain input {
		type filter hook input priority 0; policy drop;
                iif "lo" accept
                ct state established,related accept;
                ip saddr 10.0.10.0/24 tcp dport 22 accept;
                tcp dport {80,443,3000,8080,9090,3001,9100,9093} accept;
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
                ct state established,related accept;
                ip saddr 10.0.0.0/16 oifname "enp0s3" accept
                ip saddr 10.0.20.11 ip daddr 10.0.30.10 tcp dport 5432 accept
                ip saddr 10.0.20.12 ip daddr 10.0.30.10 tcp dport 5432 accept
                ip saddr 10.0.20.0/24 ip daddr 10.0.40.10 tcp dport 2049 accept
                ip saddr 10.0.40.10 ip daddr 10.0.20.0/24 tcp dport 9100 accept
                ip saddr 10.0.40.10 ip daddr 10.0.30.10 tcp dport 9187 accept
                ip saddr 10.0.40.10 ip daddr 10.0.20.10 tcp dport 6443 accept
                ip daddr 10.0.20.11 tcp dport 30050 accept
                ip daddr 10.0.40.10 tcp dport { 3000, 8080, 9090, 3001, 9093 } accept
	}
	chain output {
		type filter hook output priority 0;
	}
}


