---
# tasks file for firewall
#
#
- name: nft rules
  ansible.builtin.file:
    path: /etc/nftables.d
    state: directory
    mode: '0755'

- name: tempalte
  ansible.builtin.template:
    src: hostfw.nft.j2
    dest: /etc/nftables.d/hostfw.nft
    validate: nft -c -f %s
    mode: '0644'
  notify: reload firewall

- name: nftables.conf loads our rules on boot
  ansible.builtin.copy:
    content: |
      #!/usr/sbin/nft -f
      include "/etc/nftables.d/*.nft"
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'

- name: service
  ansible.builtin.service:
    name: nftables
    state: started
    enabled: true

