---

ansible_host: 10.0.10.13

network_connections:
  - conn_name: "mgmt"
    ifname: "enp0s8"
    ipv4_address: "10.0.10.13/24"
    dns: "{{ dns_server }}"

  - conn_name: "db"
    ifname: "enp0s9.30"
    vlan: 30
    ipv4_address: "10.0.30.10/24"
    ipv4_gateway: "10.0.30.1"
    dns: "{{ dns_server }}"

